2024-08-28 09:03:37.393 [background-preinit] INFO  org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.2.4.Final
2024-08-28 09:03:37.409 [main] INFO  i.thoughtware.xmonitor.starter.XMonitorApplication - Starting XMonitorApplication using Java 17.0.9 on DESKTOP-QSSU4I0 with PID 31156 (D:\code\companycode\xmonitor\thoughtware-xmonitor\thoughtware-xmonitor-starter\target\classes started by admin in D:\code\companycode\xmonitor\thoughtware-xmonitor-cloud)
2024-08-28 09:03:37.409 [main] INFO  i.thoughtware.xmonitor.starter.XMonitorApplication - No active profile set, falling back to default profiles: default
2024-08-28 09:03:38.249 [main] INFO  o.s.c.annotation.ConfigurationClassPostProcessor - Cannot enhance @Configuration bean definition 'io.thoughtware.rpc.boot.starter.config.RpcServerAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2024-08-28 09:03:38.380 [main] INFO  io.thoughtware.rpc.common.support.NetworkUtils - get ip adress,costTime:0
2024-08-28 09:03:38.383 [main] INFO  i.thoughtware.toolkit.context.AppHomeConfiguration - APP_HOME:D:\code\companycode\xmonitor\thoughtware-xmonitor\thoughtware-xmonitor-starter
2024-08-28 09:03:38.385 [main] INFO  i.t.plugin.core.process.PluginLoaderProcessor - plugin load...
2024-08-28 09:03:38.388 [main] INFO  i.t.plugin.core.process.PluginInstallProcessor - eas.embbed.enable:true
2024-08-28 09:03:39.454 [main] INFO  o.s.boot.web.embedded.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8080 (http)
2024-08-28 09:03:39.462 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
2024-08-28 09:03:39.463 [main] INFO  org.apache.catalina.core.StandardService - Starting service [Tomcat]
2024-08-28 09:03:39.463 [main] INFO  org.apache.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.54]
2024-08-28 09:03:39.562 [main] INFO  o.a.c.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
2024-08-28 09:03:39.562 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 2118 ms
2024-08-28 09:03:40.869 [main] INFO  i.t.r.b.starter.config.RpcServerAutoConfiguration - rpc server started on 127.0.0.1:8080
2024-08-28 09:03:41.156 [main] INFO  i.t.r.transport.tcp.transport.netty.NettyServer - netty server starting on port:5030
2024-08-28 09:03:41.241 [main] INFO  i.t.d.b.starter.config.DcsServerAutoConfiguration - dcs server started on 127.0.0.1:5030
2024-08-28 09:03:41.241 [nioEventLoopGroup-2-1] INFO  i.t.r.transport.tcp.transport.netty.NettyServer - netty started succefully.
2024-08-28 09:03:41.243 [main] INFO  i.t.postgresql.config.ExecPostgresqlScript - postgresql type local
2024-08-28 09:03:41.442 [main] INFO  o.s.b.a.web.servlet.WelcomePageHandlerMapping - Adding welcome page: class path resource [static/index.html]
2024-08-28 09:03:41.597 [main] WARN  o.s.b.a.freemarker.FreeMarkerAutoConfiguration - Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)
2024-08-28 09:03:41.651 [main] INFO  org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
2024-08-28 09:03:41.660 [main] INFO  org.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2024-08-28 09:03:41.661 [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.3.2 created.
2024-08-28 09:03:41.661 [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
2024-08-28 09:03:41.661 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.3.2) 'quartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2024-08-28 09:03:41.661 [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'quartzScheduler' initialized from an externally provided properties instance.
2024-08-28 09:03:41.662 [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.3.2
2024-08-28 09:03:41.662 [main] INFO  org.quartz.core.QuartzScheduler - JobFactory set to: org.springframework.scheduling.quartz.SpringBeanJobFactory@11e02b0
2024-08-28 09:03:41.697 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
2024-08-28 09:03:41.705 [main] INFO  o.s.boot.web.embedded.tomcat.TomcatWebServer - Tomcat started on port(s): 8080 (http) with context path ''
2024-08-28 09:03:41.706 [main] INFO  o.s.scheduling.quartz.SchedulerFactoryBean - Starting Quartz Scheduler now
2024-08-28 09:03:41.706 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler quartzScheduler_$_NON_CLUSTERED started.
2024-08-28 09:03:41.710 [main] INFO  o.s.s.a.ScheduledAnnotationBeanPostProcessor - No TaskScheduler/ScheduledExecutorService bean found for scheduled processing
2024-08-28 09:03:41.713 [main] INFO  i.t.dsm.boot.starter.config.DsmAutoConfiguration - init database...
2024-08-28 09:03:42.000 [main] WARN  io.thoughtware.dsm.config.SQLFileParser - sql script file name invalid,file name:xmonitor_update_1.0.1.sql
2024-08-28 09:03:42.083 [main] INFO  io.thoughtware.dsm.executer.SQLFileExecuter - execute sql command:INSERT INTO "pcs_mec_message_notice" ("id", "message_type_id", "type", "bgroup", "message_send_type_id", "scope", "is_open") VALUES ('1a7eb55fcc03', '5b6767f3981a', 1, 'xmonitor', 'qywechat', 1, 'true') 
2024-08-28 09:03:42.126 [main] INFO  io.thoughtware.dsm.executer.SQLFileExecuter - execute sql command failed,command:INSERT INTO "pcs_mec_message_notice" ("id", "message_type_id", "type", "bgroup", "message_send_type_id", "scope", "is_open") VALUES ('1a7eb55fcc03', '5b6767f3981a', 1, 'xmonitor', 'qywechat', 1, 'true') 
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pcs_mec_message_notice_pkey"
  详细：Key (id)=(1a7eb55fcc03) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:270)
	at io.thoughtware.dsm.executer.SQLFileExecuter.executeCommand(SQLFileExecuter.java:97)
	at io.thoughtware.dsm.executer.SQLFileExecuter.executeFile(SQLFileExecuter.java:54)
	at io.thoughtware.dsm.DsmProcessor.executeSQLFile(DsmProcessor.java:99)
	at io.thoughtware.dsm.DsmProcessor.process(DsmProcessor.java:81)
	at io.thoughtware.dsm.boot.starter.config.DsmAutoConfiguration.process(DsmAutoConfiguration.java:68)
	at io.thoughtware.dsm.boot.starter.config.DsmAutoConfiguration.onApplicationEvent(DsmAutoConfiguration.java:48)
	at io.thoughtware.dsm.boot.starter.config.DsmAutoConfiguration.onApplicationEvent(DsmAutoConfiguration.java:16)
	at io.thoughtware.dsm.boot.starter.config.DsmAutoConfiguration$$EnhancerBySpringCGLIB$$54381a03.onApplicationEvent(<generated>)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at io.thoughtware.kaelthas.starter.KaelthasApplication.main(XMonitorApplication.java:18)
2024-08-28 09:03:42.136 [main] ERROR i.t.dsm.boot.starter.config.DsmAutoConfiguration - init database failed.
io.thoughtware.core.exception.SystemException: execute sql file failed,file:xmonitor_1.0.8.sql
	at io.thoughtware.dsm.executer.SQLFileExecuter.executeFile(SQLFileExecuter.java:76)
	at io.thoughtware.dsm.DsmProcessor.executeSQLFile(DsmProcessor.java:99)
	at io.thoughtware.dsm.DsmProcessor.process(DsmProcessor.java:81)
	at io.thoughtware.dsm.boot.starter.config.DsmAutoConfiguration.process(DsmAutoConfiguration.java:68)
	at io.thoughtware.dsm.boot.starter.config.DsmAutoConfiguration.onApplicationEvent(DsmAutoConfiguration.java:48)
	at io.thoughtware.dsm.boot.starter.config.DsmAutoConfiguration.onApplicationEvent(DsmAutoConfiguration.java:16)
	at io.thoughtware.dsm.boot.starter.config.DsmAutoConfiguration$$EnhancerBySpringCGLIB$$54381a03.onApplicationEvent(<generated>)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at io.thoughtware.kaelthas.starter.KaelthasApplication.main(XMonitorApplication.java:18)
Caused by: io.thoughtware.core.exception.SystemException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pcs_mec_message_notice_pkey"
  详细：Key (id)=(1a7eb55fcc03) already exists.
	at io.thoughtware.dsm.executer.SQLFileExecuter.executeCommand(SQLFileExecuter.java:100)
	at io.thoughtware.dsm.executer.SQLFileExecuter.executeFile(SQLFileExecuter.java:54)
	... 20 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pcs_mec_message_notice_pkey"
  详细：Key (id)=(1a7eb55fcc03) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:270)
	at io.thoughtware.dsm.executer.SQLFileExecuter.executeCommand(SQLFileExecuter.java:97)
	... 21 common frames omitted
2024-08-28 09:03:42.141 [main] INFO  i.thoughtware.xmonitor.starter.XMonitorApplication - Started XMonitorApplication in 5.044 seconds (JVM running for 5.758)
